project:
  type: website
  output-dir: docs

website:
  title: "Interactive Python Slides"
  navbar: false

format:
  revealjs:
    theme: default
    transition: slide
    background-transition: fade
    highlight-style: github
    code-line-numbers: true
    scrollable: true
    controls: true
    navigation-mode: vertical